// AppleScript templates for Logic Pro automation
// These scripts are injected at runtime with actual track names

const scripts = {

  // Check if Logic is open and a project is loaded
  checkProject: () => `
tell application "Logic Pro"
  if (count of documents) > 0 then
    return name of document 1
  else
    return "NO_PROJECT"
  end if
end tell
`,

  // Open Logic if not running
  openLogic: () => `
tell application "Logic Pro"
  activate
end tell
delay 2
`,

  // Mute specific tracks by name, unmute all others
  // Returns AppleScript to set up mute state
  setupMuteState: (muteTrackNames, allTrackNames) => {
    const muteList = muteTrackNames.map(n => `"${n}"`).join(', ');
    return `
tell application "System Events"
  tell process "Logic Pro"
    -- This uses accessibility to click mute buttons
    -- Logic Pro must be frontmost
  end tell
end tell
`;
  },

  // The real approach: use Logic's built-in keyboard shortcuts
  // Solo each track group and bounce
  bounceViaKeyboard: (outputPath, format) => `
tell application "Logic Pro"
  activate
end tell
delay 0.5

tell application "System Events"
  tell process "Logic Pro"
    -- Select all tracks: Cmd+A
    keystroke "a" using command down
    delay 0.3
    -- Open bounce dialog: Cmd+B  
    keystroke "b" using command down
    delay 1
  end tell
end tell
`,

  // Full stem bounce sequence
  // muteGroups: [{name: "NO Drums", mutedTracks: ["Kick","Snare","Hi-Hats"]}]
  stemBounce: (preset, outputFolder) => `
-- Stem Bouncer: ${preset.name}
-- Generated by Stem Bouncer app

tell application "Logic Pro"
  activate
end tell
delay 0.8

-- Open the Bounce window
tell application "System Events"
  tell process "Logic Pro"
    keystroke "b" using command down
  end tell
end tell
delay 1.5

-- Set output path via dialog if needed
display dialog "Ready to bounce: ${preset.name}\\n\\nOutput: ${outputFolder}\\n\\nClick OK then confirm in Logic's bounce dialog." buttons {"Cancel", "OK"} default button "OK"
`,

};

module.exports = scripts;
